<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<%response.buffer = true
response.Expires = 0
'IF INSTR(SESSION("FUNCAO"),"-6-")<1 THEN
'   RESPONSE.REDIRECT("NEGADO1.ASP")
'END IF
%>
<html>
<head>
<title>Documento sem t&iacute;tulo</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="css/STYLE.CSS" rel="stylesheet" type="text/css">
</head>
<body background="images/FUNDOGS.GIF" text="#FFFFFF" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<div align="center"></div>
<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
  <tr>
    <td> <img src="images/BANNER1.gif" width="800" height="70"><br><br>
	<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="800" height="450">
      <param name="movie" value="images/menu116.swf">
      <param name="quality" value="high">
      <embed src="images/menu116.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="800" height="450"></embed>
    </object>
    </td>
  </tr>
</table>
<p align="center"><br>
<a href="MENUPRINCIPAL.ASP"><img src="images/seta03.gif" width="33" height="33" border="0"></a></p>
</body>
</html>
