<?xml version="1.0" encoding="utf-8"?><Database Name="Senac" Class="FrequenciaDocenteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Senac;Persist Security Info=True;User ID=sa" SettingsObjectName="Settings" SettingsPropertyName="SenacConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Parametros" Member="Parametros">
    <Type Name="Parametro">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ano" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Versao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="JN_MI_VA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAA_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAA_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAI_VT_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAI_VT_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PCO_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PCO_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_MN_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_MN_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_NT_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_NT_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_TD_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_TD_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VL_CT_VT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VL_UN_AA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataHoraRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Parametro_AgendaExecutada" Member="AgendaExecutadas" ThisKey="Id" OtherKey="IdParametro" Type="AgendaExecutada" />
    </Type>
  </Table>
  <Table Name="dbo.AgendaExecutada" Member="AgendaExecutadas">
    <Type Name="AgendaExecutada">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Unidade" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="HoraInicial" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="HoraFinal" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Disciplina" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Turma" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SalarioHora" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Matricula" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="UsuarioRegistro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataHoraRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdParametro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ArquivoDownload" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="AgendaExecutada_RegistroVT" Member="RegistroVTs" ThisKey="Id" OtherKey="IdAgendaExecutada" Type="RegistroVT" />
      <Association Name="Parametro_AgendaExecutada" Member="Parametro" ThisKey="IdParametro" OtherKey="Id" Type="Parametro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegistroVT" Member="RegistroVTs">
    <Type Name="RegistroVT">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdAgendaExecutada" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdaVolta" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ValorVT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DataHora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AgendaExecutada_RegistroVT" Member="AgendaExecutada" ThisKey="IdAgendaExecutada" OtherKey="Id" Type="AgendaExecutada" IsForeignKey="true" />
    </Type>
  </Table>
</Database>