#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.ControleRHDocente
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FrequenciaDocente")]
	public partial class FrequenciaDocenteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParametro(Parametro instance);
    partial void UpdateParametro(Parametro instance);
    partial void DeleteParametro(Parametro instance);
    #endregion
		
		public FrequenciaDocenteDataContext() : 
				base(global::Senac.ControleRHDocente.Properties.Settings.Default.FrequenciaDocenteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Parametro> Parametros
		{
			get
			{
				return this.GetTable<Parametro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parametros")]
	public partial class Parametro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ParametroField;
		
		private string _Value;
		
		private string _UsuarioRegistro;
		
		private System.Nullable<System.DateTime> _DataHora;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnParametroFieldChanging(string value);
    partial void OnParametroFieldChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    partial void OnUsuarioRegistroChanging(string value);
    partial void OnUsuarioRegistroChanged();
    partial void OnDataHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraChanged();
    #endregion
		
		public Parametro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Parametro", Storage="_ParametroField", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ParametroField
		{
			get
			{
				return this._ParametroField;
			}
			set
			{
				if ((this._ParametroField != value))
				{
					this.OnParametroFieldChanging(value);
					this.SendPropertyChanging();
					this._ParametroField = value;
					this.SendPropertyChanged("ParametroField");
					this.OnParametroFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(50)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioRegistro", DbType="VarChar(10)")]
		public string UsuarioRegistro
		{
			get
			{
				return this._UsuarioRegistro;
			}
			set
			{
				if ((this._UsuarioRegistro != value))
				{
					this.OnUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._UsuarioRegistro = value;
					this.SendPropertyChanged("UsuarioRegistro");
					this.OnUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHora
		{
			get
			{
				return this._DataHora;
			}
			set
			{
				if ((this._DataHora != value))
				{
					this.OnDataHoraChanging(value);
					this.SendPropertyChanging();
					this._DataHora = value;
					this.SendPropertyChanged("DataHora");
					this.OnDataHoraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
