<?xml version="1.0" encoding="utf-8"?><Database Name="Senac" Class="FrequenciaDocenteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Senac;Persist Security Info=True;User ID=sa" SettingsObjectName="Senac.ControleRHDocente.Properties.Settings" SettingsPropertyName="SenacConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Parametros" Member="Parametros">
    <Type Name="Parametro">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ano" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Versao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="JN_MI_VA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAA_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAA_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAI_VT_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAI_VT_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PCO_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PCO_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_MN_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_MN_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_NT_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_NT_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_TD_ATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TN_TD_DE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VL_CT_VT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VL_UN_AA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataHoraRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AgendaExecutada" Member="AgendaExecutadas">
    <Type Name="AgendaExecutada">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Valor" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
</Database>