#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senac.ControleRHDocente
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Senac")]
	public partial class FrequenciaDocenteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParametro(Parametro instance);
    partial void UpdateParametro(Parametro instance);
    partial void DeleteParametro(Parametro instance);
    partial void InsertAgendaExecutada(AgendaExecutada instance);
    partial void UpdateAgendaExecutada(AgendaExecutada instance);
    partial void DeleteAgendaExecutada(AgendaExecutada instance);
    partial void InsertAgendaExecutadaVT(AgendaExecutadaVT instance);
    partial void UpdateAgendaExecutadaVT(AgendaExecutadaVT instance);
    partial void DeleteAgendaExecutadaVT(AgendaExecutadaVT instance);
    partial void InsertAtividadeAcademica(AtividadeAcademica instance);
    partial void UpdateAtividadeAcademica(AtividadeAcademica instance);
    partial void DeleteAtividadeAcademica(AtividadeAcademica instance);
    partial void InsertCoordenacao(Coordenacao instance);
    partial void UpdateCoordenacao(Coordenacao instance);
    partial void DeleteCoordenacao(Coordenacao instance);
    #endregion
		
		public FrequenciaDocenteDataContext() : 
				base("", mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrequenciaDocenteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Parametro> Parametros
		{
			get
			{
				return this.GetTable<Parametro>();
			}
		}
		
		public System.Data.Linq.Table<AgendaExecutada> AgendaExecutadas
		{
			get
			{
				return this.GetTable<AgendaExecutada>();
			}
		}
		
		public System.Data.Linq.Table<AgendaExecutadaVT> AgendaExecutadaVTs
		{
			get
			{
				return this.GetTable<AgendaExecutadaVT>();
			}
		}
		
		public System.Data.Linq.Table<AtividadeAcademica> AtividadeAcademicas
		{
			get
			{
				return this.GetTable<AtividadeAcademica>();
			}
		}
		
		public System.Data.Linq.Table<Coordenacao> Coordenacaos
		{
			get
			{
				return this.GetTable<Coordenacao>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parametros")]
	public partial class Parametro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private System.Nullable<int> _Mes;
		
		private System.Nullable<int> _Ano;
		
		private System.Nullable<int> _Versao;
		
		private System.Nullable<bool> _Ativo;
		
		private string _JN_MI_VA;
		
		private string _PAA_ATE;
		
		private string _PAA_DE;
		
		private string _PAI_VT_ATE;
		
		private string _PAI_VT_DE;
		
		private string _PCO_ATE;
		
		private string _PCO_DE;
		
		private string _TN_MN_ATE;
		
		private string _TN_MN_DE;
		
		private string _TN_NT_ATE;
		
		private string _TN_NT_DE;
		
		private string _TN_TD_ATE;
		
		private string _TN_TD_DE;
		
		private string _VL_CT_VT;
		
		private string _VL_UN_AA;
		
		private string _Usuario;
		
		private System.Nullable<System.DateTime> _DataHoraRegistro;
		
		private EntitySet<AgendaExecutada> _AgendaExecutadas;
		
		private EntitySet<AgendaExecutadaVT> _AgendaExecutadaVTs;
		
		private EntitySet<AtividadeAcademica> _AtividadeAcademicas;
		
		private EntitySet<Coordenacao> _Coordenacaos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnMesChanging(System.Nullable<int> value);
    partial void OnMesChanged();
    partial void OnAnoChanging(System.Nullable<int> value);
    partial void OnAnoChanged();
    partial void OnVersaoChanging(System.Nullable<int> value);
    partial void OnVersaoChanged();
    partial void OnAtivoChanging(System.Nullable<bool> value);
    partial void OnAtivoChanged();
    partial void OnJN_MI_VAChanging(string value);
    partial void OnJN_MI_VAChanged();
    partial void OnPAA_ATEChanging(string value);
    partial void OnPAA_ATEChanged();
    partial void OnPAA_DEChanging(string value);
    partial void OnPAA_DEChanged();
    partial void OnPAI_VT_ATEChanging(string value);
    partial void OnPAI_VT_ATEChanged();
    partial void OnPAI_VT_DEChanging(string value);
    partial void OnPAI_VT_DEChanged();
    partial void OnPCO_ATEChanging(string value);
    partial void OnPCO_ATEChanged();
    partial void OnPCO_DEChanging(string value);
    partial void OnPCO_DEChanged();
    partial void OnTN_MN_ATEChanging(string value);
    partial void OnTN_MN_ATEChanged();
    partial void OnTN_MN_DEChanging(string value);
    partial void OnTN_MN_DEChanged();
    partial void OnTN_NT_ATEChanging(string value);
    partial void OnTN_NT_ATEChanged();
    partial void OnTN_NT_DEChanging(string value);
    partial void OnTN_NT_DEChanged();
    partial void OnTN_TD_ATEChanging(string value);
    partial void OnTN_TD_ATEChanged();
    partial void OnTN_TD_DEChanging(string value);
    partial void OnTN_TD_DEChanged();
    partial void OnVL_CT_VTChanging(string value);
    partial void OnVL_CT_VTChanged();
    partial void OnVL_UN_AAChanging(string value);
    partial void OnVL_UN_AAChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnDataHoraRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraRegistroChanged();
    #endregion
		
		public Parametro()
		{
			this._AgendaExecutadas = new EntitySet<AgendaExecutada>(new Action<AgendaExecutada>(this.attach_AgendaExecutadas), new Action<AgendaExecutada>(this.detach_AgendaExecutadas));
			this._AgendaExecutadaVTs = new EntitySet<AgendaExecutadaVT>(new Action<AgendaExecutadaVT>(this.attach_AgendaExecutadaVTs), new Action<AgendaExecutadaVT>(this.detach_AgendaExecutadaVTs));
			this._AtividadeAcademicas = new EntitySet<AtividadeAcademica>(new Action<AtividadeAcademica>(this.attach_AtividadeAcademicas), new Action<AtividadeAcademica>(this.detach_AtividadeAcademicas));
			this._Coordenacaos = new EntitySet<Coordenacao>(new Action<Coordenacao>(this.attach_Coordenacaos), new Action<Coordenacao>(this.detach_Coordenacaos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mes", DbType="Int")]
		public System.Nullable<int> Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this.OnMesChanging(value);
					this.SendPropertyChanging();
					this._Mes = value;
					this.SendPropertyChanged("Mes");
					this.OnMesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ano", DbType="Int")]
		public System.Nullable<int> Ano
		{
			get
			{
				return this._Ano;
			}
			set
			{
				if ((this._Ano != value))
				{
					this.OnAnoChanging(value);
					this.SendPropertyChanging();
					this._Ano = value;
					this.SendPropertyChanged("Ano");
					this.OnAnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Versao", DbType="Int")]
		public System.Nullable<int> Versao
		{
			get
			{
				return this._Versao;
			}
			set
			{
				if ((this._Versao != value))
				{
					this.OnVersaoChanging(value);
					this.SendPropertyChanging();
					this._Versao = value;
					this.SendPropertyChanged("Versao");
					this.OnVersaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit")]
		public System.Nullable<bool> Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JN_MI_VA", DbType="VarChar(50)")]
		public string JN_MI_VA
		{
			get
			{
				return this._JN_MI_VA;
			}
			set
			{
				if ((this._JN_MI_VA != value))
				{
					this.OnJN_MI_VAChanging(value);
					this.SendPropertyChanging();
					this._JN_MI_VA = value;
					this.SendPropertyChanged("JN_MI_VA");
					this.OnJN_MI_VAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAA_ATE", DbType="VarChar(50)")]
		public string PAA_ATE
		{
			get
			{
				return this._PAA_ATE;
			}
			set
			{
				if ((this._PAA_ATE != value))
				{
					this.OnPAA_ATEChanging(value);
					this.SendPropertyChanging();
					this._PAA_ATE = value;
					this.SendPropertyChanged("PAA_ATE");
					this.OnPAA_ATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAA_DE", DbType="VarChar(50)")]
		public string PAA_DE
		{
			get
			{
				return this._PAA_DE;
			}
			set
			{
				if ((this._PAA_DE != value))
				{
					this.OnPAA_DEChanging(value);
					this.SendPropertyChanging();
					this._PAA_DE = value;
					this.SendPropertyChanged("PAA_DE");
					this.OnPAA_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAI_VT_ATE", DbType="VarChar(50)")]
		public string PAI_VT_ATE
		{
			get
			{
				return this._PAI_VT_ATE;
			}
			set
			{
				if ((this._PAI_VT_ATE != value))
				{
					this.OnPAI_VT_ATEChanging(value);
					this.SendPropertyChanging();
					this._PAI_VT_ATE = value;
					this.SendPropertyChanged("PAI_VT_ATE");
					this.OnPAI_VT_ATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAI_VT_DE", DbType="VarChar(50)")]
		public string PAI_VT_DE
		{
			get
			{
				return this._PAI_VT_DE;
			}
			set
			{
				if ((this._PAI_VT_DE != value))
				{
					this.OnPAI_VT_DEChanging(value);
					this.SendPropertyChanging();
					this._PAI_VT_DE = value;
					this.SendPropertyChanged("PAI_VT_DE");
					this.OnPAI_VT_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCO_ATE", DbType="VarChar(50)")]
		public string PCO_ATE
		{
			get
			{
				return this._PCO_ATE;
			}
			set
			{
				if ((this._PCO_ATE != value))
				{
					this.OnPCO_ATEChanging(value);
					this.SendPropertyChanging();
					this._PCO_ATE = value;
					this.SendPropertyChanged("PCO_ATE");
					this.OnPCO_ATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCO_DE", DbType="VarChar(50)")]
		public string PCO_DE
		{
			get
			{
				return this._PCO_DE;
			}
			set
			{
				if ((this._PCO_DE != value))
				{
					this.OnPCO_DEChanging(value);
					this.SendPropertyChanging();
					this._PCO_DE = value;
					this.SendPropertyChanged("PCO_DE");
					this.OnPCO_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_MN_ATE", DbType="VarChar(50)")]
		public string TN_MN_ATE
		{
			get
			{
				return this._TN_MN_ATE;
			}
			set
			{
				if ((this._TN_MN_ATE != value))
				{
					this.OnTN_MN_ATEChanging(value);
					this.SendPropertyChanging();
					this._TN_MN_ATE = value;
					this.SendPropertyChanged("TN_MN_ATE");
					this.OnTN_MN_ATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_MN_DE", DbType="VarChar(50)")]
		public string TN_MN_DE
		{
			get
			{
				return this._TN_MN_DE;
			}
			set
			{
				if ((this._TN_MN_DE != value))
				{
					this.OnTN_MN_DEChanging(value);
					this.SendPropertyChanging();
					this._TN_MN_DE = value;
					this.SendPropertyChanged("TN_MN_DE");
					this.OnTN_MN_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_NT_ATE", DbType="VarChar(50)")]
		public string TN_NT_ATE
		{
			get
			{
				return this._TN_NT_ATE;
			}
			set
			{
				if ((this._TN_NT_ATE != value))
				{
					this.OnTN_NT_ATEChanging(value);
					this.SendPropertyChanging();
					this._TN_NT_ATE = value;
					this.SendPropertyChanged("TN_NT_ATE");
					this.OnTN_NT_ATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_NT_DE", DbType="VarChar(50)")]
		public string TN_NT_DE
		{
			get
			{
				return this._TN_NT_DE;
			}
			set
			{
				if ((this._TN_NT_DE != value))
				{
					this.OnTN_NT_DEChanging(value);
					this.SendPropertyChanging();
					this._TN_NT_DE = value;
					this.SendPropertyChanged("TN_NT_DE");
					this.OnTN_NT_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_TD_ATE", DbType="VarChar(50)")]
		public string TN_TD_ATE
		{
			get
			{
				return this._TN_TD_ATE;
			}
			set
			{
				if ((this._TN_TD_ATE != value))
				{
					this.OnTN_TD_ATEChanging(value);
					this.SendPropertyChanging();
					this._TN_TD_ATE = value;
					this.SendPropertyChanged("TN_TD_ATE");
					this.OnTN_TD_ATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_TD_DE", DbType="VarChar(50)")]
		public string TN_TD_DE
		{
			get
			{
				return this._TN_TD_DE;
			}
			set
			{
				if ((this._TN_TD_DE != value))
				{
					this.OnTN_TD_DEChanging(value);
					this.SendPropertyChanging();
					this._TN_TD_DE = value;
					this.SendPropertyChanged("TN_TD_DE");
					this.OnTN_TD_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_CT_VT", DbType="VarChar(50)")]
		public string VL_CT_VT
		{
			get
			{
				return this._VL_CT_VT;
			}
			set
			{
				if ((this._VL_CT_VT != value))
				{
					this.OnVL_CT_VTChanging(value);
					this.SendPropertyChanging();
					this._VL_CT_VT = value;
					this.SendPropertyChanged("VL_CT_VT");
					this.OnVL_CT_VTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_UN_AA", DbType="VarChar(50)")]
		public string VL_UN_AA
		{
			get
			{
				return this._VL_UN_AA;
			}
			set
			{
				if ((this._VL_UN_AA != value))
				{
					this.OnVL_UN_AAChanging(value);
					this.SendPropertyChanging();
					this._VL_UN_AA = value;
					this.SendPropertyChanged("VL_UN_AA");
					this.OnVL_UN_AAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraRegistro
		{
			get
			{
				return this._DataHoraRegistro;
			}
			set
			{
				if ((this._DataHoraRegistro != value))
				{
					this.OnDataHoraRegistroChanging(value);
					this.SendPropertyChanging();
					this._DataHoraRegistro = value;
					this.SendPropertyChanged("DataHoraRegistro");
					this.OnDataHoraRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_AgendaExecutada", Storage="_AgendaExecutadas", ThisKey="Id", OtherKey="IdParametro")]
		public EntitySet<AgendaExecutada> AgendaExecutadas
		{
			get
			{
				return this._AgendaExecutadas;
			}
			set
			{
				this._AgendaExecutadas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_AgendaExecutadaVT", Storage="_AgendaExecutadaVTs", ThisKey="Id", OtherKey="IdParametro")]
		public EntitySet<AgendaExecutadaVT> AgendaExecutadaVTs
		{
			get
			{
				return this._AgendaExecutadaVTs;
			}
			set
			{
				this._AgendaExecutadaVTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_AtividadeAcademica", Storage="_AtividadeAcademicas", ThisKey="Id", OtherKey="IdParametro")]
		public EntitySet<AtividadeAcademica> AtividadeAcademicas
		{
			get
			{
				return this._AtividadeAcademicas;
			}
			set
			{
				this._AtividadeAcademicas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_Coordenacao", Storage="_Coordenacaos", ThisKey="Id", OtherKey="IdParametro")]
		public EntitySet<Coordenacao> Coordenacaos
		{
			get
			{
				return this._Coordenacaos;
			}
			set
			{
				this._Coordenacaos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AgendaExecutadas(AgendaExecutada entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = this;
		}
		
		private void detach_AgendaExecutadas(AgendaExecutada entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = null;
		}
		
		private void attach_AgendaExecutadaVTs(AgendaExecutadaVT entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = this;
		}
		
		private void detach_AgendaExecutadaVTs(AgendaExecutadaVT entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = null;
		}
		
		private void attach_AtividadeAcademicas(AtividadeAcademica entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = this;
		}
		
		private void detach_AtividadeAcademicas(AtividadeAcademica entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = null;
		}
		
		private void attach_Coordenacaos(Coordenacao entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = this;
		}
		
		private void detach_Coordenacaos(Coordenacao entity)
		{
			this.SendPropertyChanging();
			entity.Parametro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AgendaExecutada")]
	public partial class AgendaExecutada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Unidade;
		
		private string _Data;
		
		private string _HoraInicial;
		
		private string _HoraFinal;
		
		private string _Disciplina;
		
		private string _Turma;
		
		private string _SalarioHora;
		
		private string _Matricula;
		
		private string _Status;
		
		private string _Categoria;
		
		private string _UsuarioRegistro;
		
		private System.Nullable<System.DateTime> _DataHoraRegistro;
		
		private string _IdParametro;
		
		private string _ArquivoDownload;
		
		private EntityRef<Parametro> _Parametro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnUnidadeChanging(string value);
    partial void OnUnidadeChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    partial void OnHoraInicialChanging(string value);
    partial void OnHoraInicialChanged();
    partial void OnHoraFinalChanging(string value);
    partial void OnHoraFinalChanged();
    partial void OnDisciplinaChanging(string value);
    partial void OnDisciplinaChanged();
    partial void OnTurmaChanging(string value);
    partial void OnTurmaChanged();
    partial void OnSalarioHoraChanging(string value);
    partial void OnSalarioHoraChanged();
    partial void OnMatriculaChanging(string value);
    partial void OnMatriculaChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnUsuarioRegistroChanging(string value);
    partial void OnUsuarioRegistroChanged();
    partial void OnDataHoraRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraRegistroChanged();
    partial void OnIdParametroChanging(string value);
    partial void OnIdParametroChanged();
    partial void OnArquivoDownloadChanging(string value);
    partial void OnArquivoDownloadChanged();
    #endregion
		
		public AgendaExecutada()
		{
			this._Parametro = default(EntityRef<Parametro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidade", DbType="VarChar(6)")]
		public string Unidade
		{
			get
			{
				return this._Unidade;
			}
			set
			{
				if ((this._Unidade != value))
				{
					this.OnUnidadeChanging(value);
					this.SendPropertyChanging();
					this._Unidade = value;
					this.SendPropertyChanged("Unidade");
					this.OnUnidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarChar(8)")]
		public string Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraInicial", DbType="VarChar(5)")]
		public string HoraInicial
		{
			get
			{
				return this._HoraInicial;
			}
			set
			{
				if ((this._HoraInicial != value))
				{
					this.OnHoraInicialChanging(value);
					this.SendPropertyChanging();
					this._HoraInicial = value;
					this.SendPropertyChanged("HoraInicial");
					this.OnHoraInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFinal", DbType="VarChar(5)")]
		public string HoraFinal
		{
			get
			{
				return this._HoraFinal;
			}
			set
			{
				if ((this._HoraFinal != value))
				{
					this.OnHoraFinalChanging(value);
					this.SendPropertyChanging();
					this._HoraFinal = value;
					this.SendPropertyChanged("HoraFinal");
					this.OnHoraFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disciplina", DbType="VarChar(20)")]
		public string Disciplina
		{
			get
			{
				return this._Disciplina;
			}
			set
			{
				if ((this._Disciplina != value))
				{
					this.OnDisciplinaChanging(value);
					this.SendPropertyChanging();
					this._Disciplina = value;
					this.SendPropertyChanged("Disciplina");
					this.OnDisciplinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turma", DbType="VarChar(20)")]
		public string Turma
		{
			get
			{
				return this._Turma;
			}
			set
			{
				if ((this._Turma != value))
				{
					this.OnTurmaChanging(value);
					this.SendPropertyChanging();
					this._Turma = value;
					this.SendPropertyChanged("Turma");
					this.OnTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalarioHora", DbType="VarChar(20)")]
		public string SalarioHora
		{
			get
			{
				return this._SalarioHora;
			}
			set
			{
				if ((this._SalarioHora != value))
				{
					this.OnSalarioHoraChanging(value);
					this.SendPropertyChanging();
					this._SalarioHora = value;
					this.SendPropertyChanged("SalarioHora");
					this.OnSalarioHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="VarChar(10)")]
		public string Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(5)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioRegistro", DbType="VarChar(50)")]
		public string UsuarioRegistro
		{
			get
			{
				return this._UsuarioRegistro;
			}
			set
			{
				if ((this._UsuarioRegistro != value))
				{
					this.OnUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._UsuarioRegistro = value;
					this.SendPropertyChanged("UsuarioRegistro");
					this.OnUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraRegistro
		{
			get
			{
				return this._DataHoraRegistro;
			}
			set
			{
				if ((this._DataHoraRegistro != value))
				{
					this.OnDataHoraRegistroChanging(value);
					this.SendPropertyChanging();
					this._DataHoraRegistro = value;
					this.SendPropertyChanged("DataHoraRegistro");
					this.OnDataHoraRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdParametro", DbType="VarChar(50)")]
		public string IdParametro
		{
			get
			{
				return this._IdParametro;
			}
			set
			{
				if ((this._IdParametro != value))
				{
					if (this._Parametro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdParametroChanging(value);
					this.SendPropertyChanging();
					this._IdParametro = value;
					this.SendPropertyChanged("IdParametro");
					this.OnIdParametroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArquivoDownload", DbType="VarChar(500)")]
		public string ArquivoDownload
		{
			get
			{
				return this._ArquivoDownload;
			}
			set
			{
				if ((this._ArquivoDownload != value))
				{
					this.OnArquivoDownloadChanging(value);
					this.SendPropertyChanging();
					this._ArquivoDownload = value;
					this.SendPropertyChanged("ArquivoDownload");
					this.OnArquivoDownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_AgendaExecutada", Storage="_Parametro", ThisKey="IdParametro", OtherKey="Id", IsForeignKey=true)]
		public Parametro Parametro
		{
			get
			{
				return this._Parametro.Entity;
			}
			set
			{
				Parametro previousValue = this._Parametro.Entity;
				if (((previousValue != value) 
							|| (this._Parametro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Parametro.Entity = null;
						previousValue.AgendaExecutadas.Remove(this);
					}
					this._Parametro.Entity = value;
					if ((value != null))
					{
						value.AgendaExecutadas.Add(this);
						this._IdParametro = value.Id;
					}
					else
					{
						this._IdParametro = default(string);
					}
					this.SendPropertyChanged("Parametro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AgendaExecutadaVT")]
	public partial class AgendaExecutadaVT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Unidade;
		
		private string _Data;
		
		private string _HoraInicial;
		
		private string _HoraFinal;
		
		private string _Disciplina;
		
		private string _Turma;
		
		private string _SalarioHora;
		
		private string _Matricula;
		
		private string _Status;
		
		private string _Categoria;
		
		private string _UsuarioRegistro;
		
		private System.Nullable<System.DateTime> _DataHoraRegistro;
		
		private string _IdParametro;
		
		private string _ArquivoDownload;
		
		private string _IdaVolta;
		
		private System.Nullable<decimal> _ValorVT;
		
		private System.Nullable<System.DateTime> _DataHoraVT;
		
		private EntityRef<Parametro> _Parametro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnUnidadeChanging(string value);
    partial void OnUnidadeChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    partial void OnHoraInicialChanging(string value);
    partial void OnHoraInicialChanged();
    partial void OnHoraFinalChanging(string value);
    partial void OnHoraFinalChanged();
    partial void OnDisciplinaChanging(string value);
    partial void OnDisciplinaChanged();
    partial void OnTurmaChanging(string value);
    partial void OnTurmaChanged();
    partial void OnSalarioHoraChanging(string value);
    partial void OnSalarioHoraChanged();
    partial void OnMatriculaChanging(string value);
    partial void OnMatriculaChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnUsuarioRegistroChanging(string value);
    partial void OnUsuarioRegistroChanged();
    partial void OnDataHoraRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraRegistroChanged();
    partial void OnIdParametroChanging(string value);
    partial void OnIdParametroChanged();
    partial void OnArquivoDownloadChanging(string value);
    partial void OnArquivoDownloadChanged();
    partial void OnIdaVoltaChanging(string value);
    partial void OnIdaVoltaChanged();
    partial void OnValorVTChanging(System.Nullable<decimal> value);
    partial void OnValorVTChanged();
    partial void OnDataHoraVTChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraVTChanged();
    #endregion
		
		public AgendaExecutadaVT()
		{
			this._Parametro = default(EntityRef<Parametro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidade", DbType="VarChar(6)")]
		public string Unidade
		{
			get
			{
				return this._Unidade;
			}
			set
			{
				if ((this._Unidade != value))
				{
					this.OnUnidadeChanging(value);
					this.SendPropertyChanging();
					this._Unidade = value;
					this.SendPropertyChanged("Unidade");
					this.OnUnidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarChar(8)")]
		public string Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraInicial", DbType="VarChar(5)")]
		public string HoraInicial
		{
			get
			{
				return this._HoraInicial;
			}
			set
			{
				if ((this._HoraInicial != value))
				{
					this.OnHoraInicialChanging(value);
					this.SendPropertyChanging();
					this._HoraInicial = value;
					this.SendPropertyChanged("HoraInicial");
					this.OnHoraInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFinal", DbType="VarChar(5)")]
		public string HoraFinal
		{
			get
			{
				return this._HoraFinal;
			}
			set
			{
				if ((this._HoraFinal != value))
				{
					this.OnHoraFinalChanging(value);
					this.SendPropertyChanging();
					this._HoraFinal = value;
					this.SendPropertyChanged("HoraFinal");
					this.OnHoraFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disciplina", DbType="VarChar(20)")]
		public string Disciplina
		{
			get
			{
				return this._Disciplina;
			}
			set
			{
				if ((this._Disciplina != value))
				{
					this.OnDisciplinaChanging(value);
					this.SendPropertyChanging();
					this._Disciplina = value;
					this.SendPropertyChanged("Disciplina");
					this.OnDisciplinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turma", DbType="VarChar(20)")]
		public string Turma
		{
			get
			{
				return this._Turma;
			}
			set
			{
				if ((this._Turma != value))
				{
					this.OnTurmaChanging(value);
					this.SendPropertyChanging();
					this._Turma = value;
					this.SendPropertyChanged("Turma");
					this.OnTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalarioHora", DbType="VarChar(20)")]
		public string SalarioHora
		{
			get
			{
				return this._SalarioHora;
			}
			set
			{
				if ((this._SalarioHora != value))
				{
					this.OnSalarioHoraChanging(value);
					this.SendPropertyChanging();
					this._SalarioHora = value;
					this.SendPropertyChanged("SalarioHora");
					this.OnSalarioHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="VarChar(10)")]
		public string Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(5)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioRegistro", DbType="VarChar(50)")]
		public string UsuarioRegistro
		{
			get
			{
				return this._UsuarioRegistro;
			}
			set
			{
				if ((this._UsuarioRegistro != value))
				{
					this.OnUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._UsuarioRegistro = value;
					this.SendPropertyChanged("UsuarioRegistro");
					this.OnUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraRegistro
		{
			get
			{
				return this._DataHoraRegistro;
			}
			set
			{
				if ((this._DataHoraRegistro != value))
				{
					this.OnDataHoraRegistroChanging(value);
					this.SendPropertyChanging();
					this._DataHoraRegistro = value;
					this.SendPropertyChanged("DataHoraRegistro");
					this.OnDataHoraRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdParametro", DbType="VarChar(50)")]
		public string IdParametro
		{
			get
			{
				return this._IdParametro;
			}
			set
			{
				if ((this._IdParametro != value))
				{
					if (this._Parametro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdParametroChanging(value);
					this.SendPropertyChanging();
					this._IdParametro = value;
					this.SendPropertyChanged("IdParametro");
					this.OnIdParametroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArquivoDownload", DbType="VarChar(500)")]
		public string ArquivoDownload
		{
			get
			{
				return this._ArquivoDownload;
			}
			set
			{
				if ((this._ArquivoDownload != value))
				{
					this.OnArquivoDownloadChanging(value);
					this.SendPropertyChanging();
					this._ArquivoDownload = value;
					this.SendPropertyChanged("ArquivoDownload");
					this.OnArquivoDownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdaVolta", DbType="VarChar(500)")]
		public string IdaVolta
		{
			get
			{
				return this._IdaVolta;
			}
			set
			{
				if ((this._IdaVolta != value))
				{
					this.OnIdaVoltaChanging(value);
					this.SendPropertyChanging();
					this._IdaVolta = value;
					this.SendPropertyChanged("IdaVolta");
					this.OnIdaVoltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorVT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorVT
		{
			get
			{
				return this._ValorVT;
			}
			set
			{
				if ((this._ValorVT != value))
				{
					this.OnValorVTChanging(value);
					this.SendPropertyChanging();
					this._ValorVT = value;
					this.SendPropertyChanged("ValorVT");
					this.OnValorVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraVT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraVT
		{
			get
			{
				return this._DataHoraVT;
			}
			set
			{
				if ((this._DataHoraVT != value))
				{
					this.OnDataHoraVTChanging(value);
					this.SendPropertyChanging();
					this._DataHoraVT = value;
					this.SendPropertyChanged("DataHoraVT");
					this.OnDataHoraVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_AgendaExecutadaVT", Storage="_Parametro", ThisKey="IdParametro", OtherKey="Id", IsForeignKey=true)]
		public Parametro Parametro
		{
			get
			{
				return this._Parametro.Entity;
			}
			set
			{
				Parametro previousValue = this._Parametro.Entity;
				if (((previousValue != value) 
							|| (this._Parametro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Parametro.Entity = null;
						previousValue.AgendaExecutadaVTs.Remove(this);
					}
					this._Parametro.Entity = value;
					if ((value != null))
					{
						value.AgendaExecutadaVTs.Add(this);
						this._IdParametro = value.Id;
					}
					else
					{
						this._IdParametro = default(string);
					}
					this.SendPropertyChanged("Parametro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AtividadeAcademica")]
	public partial class AtividadeAcademica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _IdUnidade;
		
		private string _Area;
		
		private System.DateTime _Data;
		
		private string _Entrada;
		
		private string _Saida;
		
		private string _Categoria;
		
		private string _Justificativas;
		
		private System.Nullable<decimal> _ValorVT;
		
		private string _TrajetoIdaVolta;
		
		private System.Nullable<bool> _Validacao;
		
		private string _UsuarioValidacao;
		
		private System.Nullable<System.DateTime> _DataHoraValidacao;
		
		private System.Nullable<System.DateTime> _DataHoraRegistro;
		
		private string _IdParametro;
		
		private EntityRef<Parametro> _Parametro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIdUnidadeChanging(string value);
    partial void OnIdUnidadeChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnEntradaChanging(string value);
    partial void OnEntradaChanged();
    partial void OnSaidaChanging(string value);
    partial void OnSaidaChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnJustificativasChanging(string value);
    partial void OnJustificativasChanged();
    partial void OnValorVTChanging(System.Nullable<decimal> value);
    partial void OnValorVTChanged();
    partial void OnTrajetoIdaVoltaChanging(string value);
    partial void OnTrajetoIdaVoltaChanged();
    partial void OnValidacaoChanging(System.Nullable<bool> value);
    partial void OnValidacaoChanged();
    partial void OnUsuarioValidacaoChanging(string value);
    partial void OnUsuarioValidacaoChanged();
    partial void OnDataHoraValidacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraValidacaoChanged();
    partial void OnDataHoraRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraRegistroChanged();
    partial void OnIdParametroChanging(string value);
    partial void OnIdParametroChanged();
    #endregion
		
		public AtividadeAcademica()
		{
			this._Parametro = default(EntityRef<Parametro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnidade", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IdUnidade
		{
			get
			{
				return this._IdUnidade;
			}
			set
			{
				if ((this._IdUnidade != value))
				{
					this.OnIdUnidadeChanging(value);
					this.SendPropertyChanging();
					this._IdUnidade = value;
					this.SendPropertyChanged("IdUnidade");
					this.OnIdUnidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this.OnEntradaChanging(value);
					this.SendPropertyChanging();
					this._Entrada = value;
					this.SendPropertyChanged("Entrada");
					this.OnEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saida", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Saida
		{
			get
			{
				return this._Saida;
			}
			set
			{
				if ((this._Saida != value))
				{
					this.OnSaidaChanging(value);
					this.SendPropertyChanging();
					this._Saida = value;
					this.SendPropertyChanged("Saida");
					this.OnSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Justificativas", DbType="VarChar(500)")]
		public string Justificativas
		{
			get
			{
				return this._Justificativas;
			}
			set
			{
				if ((this._Justificativas != value))
				{
					this.OnJustificativasChanging(value);
					this.SendPropertyChanging();
					this._Justificativas = value;
					this.SendPropertyChanged("Justificativas");
					this.OnJustificativasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorVT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorVT
		{
			get
			{
				return this._ValorVT;
			}
			set
			{
				if ((this._ValorVT != value))
				{
					this.OnValorVTChanging(value);
					this.SendPropertyChanging();
					this._ValorVT = value;
					this.SendPropertyChanged("ValorVT");
					this.OnValorVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrajetoIdaVolta", DbType="VarChar(500)")]
		public string TrajetoIdaVolta
		{
			get
			{
				return this._TrajetoIdaVolta;
			}
			set
			{
				if ((this._TrajetoIdaVolta != value))
				{
					this.OnTrajetoIdaVoltaChanging(value);
					this.SendPropertyChanging();
					this._TrajetoIdaVolta = value;
					this.SendPropertyChanged("TrajetoIdaVolta");
					this.OnTrajetoIdaVoltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validacao", DbType="Bit")]
		public System.Nullable<bool> Validacao
		{
			get
			{
				return this._Validacao;
			}
			set
			{
				if ((this._Validacao != value))
				{
					this.OnValidacaoChanging(value);
					this.SendPropertyChanging();
					this._Validacao = value;
					this.SendPropertyChanged("Validacao");
					this.OnValidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioValidacao", DbType="VarChar(50)")]
		public string UsuarioValidacao
		{
			get
			{
				return this._UsuarioValidacao;
			}
			set
			{
				if ((this._UsuarioValidacao != value))
				{
					this.OnUsuarioValidacaoChanging(value);
					this.SendPropertyChanging();
					this._UsuarioValidacao = value;
					this.SendPropertyChanged("UsuarioValidacao");
					this.OnUsuarioValidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraValidacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraValidacao
		{
			get
			{
				return this._DataHoraValidacao;
			}
			set
			{
				if ((this._DataHoraValidacao != value))
				{
					this.OnDataHoraValidacaoChanging(value);
					this.SendPropertyChanging();
					this._DataHoraValidacao = value;
					this.SendPropertyChanged("DataHoraValidacao");
					this.OnDataHoraValidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraRegistro
		{
			get
			{
				return this._DataHoraRegistro;
			}
			set
			{
				if ((this._DataHoraRegistro != value))
				{
					this.OnDataHoraRegistroChanging(value);
					this.SendPropertyChanging();
					this._DataHoraRegistro = value;
					this.SendPropertyChanged("DataHoraRegistro");
					this.OnDataHoraRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdParametro", DbType="VarChar(50)")]
		public string IdParametro
		{
			get
			{
				return this._IdParametro;
			}
			set
			{
				if ((this._IdParametro != value))
				{
					if (this._Parametro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdParametroChanging(value);
					this.SendPropertyChanging();
					this._IdParametro = value;
					this.SendPropertyChanged("IdParametro");
					this.OnIdParametroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_AtividadeAcademica", Storage="_Parametro", ThisKey="IdParametro", OtherKey="Id", IsForeignKey=true)]
		public Parametro Parametro
		{
			get
			{
				return this._Parametro.Entity;
			}
			set
			{
				Parametro previousValue = this._Parametro.Entity;
				if (((previousValue != value) 
							|| (this._Parametro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Parametro.Entity = null;
						previousValue.AtividadeAcademicas.Remove(this);
					}
					this._Parametro.Entity = value;
					if ((value != null))
					{
						value.AtividadeAcademicas.Add(this);
						this._IdParametro = value.Id;
					}
					else
					{
						this._IdParametro = default(string);
					}
					this.SendPropertyChanged("Parametro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Coordenacao")]
	public partial class Coordenacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _IdUnidade;
		
		private string _Area;
		
		private System.DateTime _Data;
		
		private string _Entrada;
		
		private string _Saida;
		
		private string _Categoria;
		
		private string _Justificativas;
		
		private System.Nullable<decimal> _ValorVT;
		
		private string _TrajetoIdaVolta;
		
		private System.Nullable<bool> _Validacao;
		
		private string _UsuarioValidacao;
		
		private System.Nullable<System.DateTime> _DataHoraValidacao;
		
		private System.Nullable<System.DateTime> _DataHoraRegistro;
		
		private string _IdParametro;
		
		private EntityRef<Parametro> _Parametro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIdUnidadeChanging(string value);
    partial void OnIdUnidadeChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnEntradaChanging(string value);
    partial void OnEntradaChanged();
    partial void OnSaidaChanging(string value);
    partial void OnSaidaChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnJustificativasChanging(string value);
    partial void OnJustificativasChanged();
    partial void OnValorVTChanging(System.Nullable<decimal> value);
    partial void OnValorVTChanged();
    partial void OnTrajetoIdaVoltaChanging(string value);
    partial void OnTrajetoIdaVoltaChanged();
    partial void OnValidacaoChanging(System.Nullable<bool> value);
    partial void OnValidacaoChanged();
    partial void OnUsuarioValidacaoChanging(string value);
    partial void OnUsuarioValidacaoChanged();
    partial void OnDataHoraValidacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraValidacaoChanged();
    partial void OnDataHoraRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataHoraRegistroChanged();
    partial void OnIdParametroChanging(string value);
    partial void OnIdParametroChanged();
    #endregion
		
		public Coordenacao()
		{
			this._Parametro = default(EntityRef<Parametro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnidade", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IdUnidade
		{
			get
			{
				return this._IdUnidade;
			}
			set
			{
				if ((this._IdUnidade != value))
				{
					this.OnIdUnidadeChanging(value);
					this.SendPropertyChanging();
					this._IdUnidade = value;
					this.SendPropertyChanged("IdUnidade");
					this.OnIdUnidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this.OnEntradaChanging(value);
					this.SendPropertyChanging();
					this._Entrada = value;
					this.SendPropertyChanged("Entrada");
					this.OnEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saida", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Saida
		{
			get
			{
				return this._Saida;
			}
			set
			{
				if ((this._Saida != value))
				{
					this.OnSaidaChanging(value);
					this.SendPropertyChanging();
					this._Saida = value;
					this.SendPropertyChanged("Saida");
					this.OnSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Justificativas", DbType="VarChar(500)")]
		public string Justificativas
		{
			get
			{
				return this._Justificativas;
			}
			set
			{
				if ((this._Justificativas != value))
				{
					this.OnJustificativasChanging(value);
					this.SendPropertyChanging();
					this._Justificativas = value;
					this.SendPropertyChanged("Justificativas");
					this.OnJustificativasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorVT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorVT
		{
			get
			{
				return this._ValorVT;
			}
			set
			{
				if ((this._ValorVT != value))
				{
					this.OnValorVTChanging(value);
					this.SendPropertyChanging();
					this._ValorVT = value;
					this.SendPropertyChanged("ValorVT");
					this.OnValorVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrajetoIdaVolta", DbType="VarChar(500)")]
		public string TrajetoIdaVolta
		{
			get
			{
				return this._TrajetoIdaVolta;
			}
			set
			{
				if ((this._TrajetoIdaVolta != value))
				{
					this.OnTrajetoIdaVoltaChanging(value);
					this.SendPropertyChanging();
					this._TrajetoIdaVolta = value;
					this.SendPropertyChanged("TrajetoIdaVolta");
					this.OnTrajetoIdaVoltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validacao", DbType="Bit")]
		public System.Nullable<bool> Validacao
		{
			get
			{
				return this._Validacao;
			}
			set
			{
				if ((this._Validacao != value))
				{
					this.OnValidacaoChanging(value);
					this.SendPropertyChanging();
					this._Validacao = value;
					this.SendPropertyChanged("Validacao");
					this.OnValidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioValidacao", DbType="VarChar(50)")]
		public string UsuarioValidacao
		{
			get
			{
				return this._UsuarioValidacao;
			}
			set
			{
				if ((this._UsuarioValidacao != value))
				{
					this.OnUsuarioValidacaoChanging(value);
					this.SendPropertyChanging();
					this._UsuarioValidacao = value;
					this.SendPropertyChanged("UsuarioValidacao");
					this.OnUsuarioValidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraValidacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraValidacao
		{
			get
			{
				return this._DataHoraValidacao;
			}
			set
			{
				if ((this._DataHoraValidacao != value))
				{
					this.OnDataHoraValidacaoChanging(value);
					this.SendPropertyChanging();
					this._DataHoraValidacao = value;
					this.SendPropertyChanged("DataHoraValidacao");
					this.OnDataHoraValidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHoraRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataHoraRegistro
		{
			get
			{
				return this._DataHoraRegistro;
			}
			set
			{
				if ((this._DataHoraRegistro != value))
				{
					this.OnDataHoraRegistroChanging(value);
					this.SendPropertyChanging();
					this._DataHoraRegistro = value;
					this.SendPropertyChanged("DataHoraRegistro");
					this.OnDataHoraRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdParametro", DbType="VarChar(50)")]
		public string IdParametro
		{
			get
			{
				return this._IdParametro;
			}
			set
			{
				if ((this._IdParametro != value))
				{
					if (this._Parametro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdParametroChanging(value);
					this.SendPropertyChanging();
					this._IdParametro = value;
					this.SendPropertyChanged("IdParametro");
					this.OnIdParametroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Parametro_Coordenacao", Storage="_Parametro", ThisKey="IdParametro", OtherKey="Id", IsForeignKey=true)]
		public Parametro Parametro
		{
			get
			{
				return this._Parametro.Entity;
			}
			set
			{
				Parametro previousValue = this._Parametro.Entity;
				if (((previousValue != value) 
							|| (this._Parametro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Parametro.Entity = null;
						previousValue.Coordenacaos.Remove(this);
					}
					this._Parametro.Entity = value;
					if ((value != null))
					{
						value.Coordenacaos.Add(this);
						this._IdParametro = value.Id;
					}
					else
					{
						this._IdParametro = default(string);
					}
					this.SendPropertyChanged("Parametro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
